export const ROUTES = {
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  stocks: "/stocks",
  stockBuy: "/stocks/buy",
  stockSell: "/stocks/sell",
  stockHoldings: "/stocks/holdings",
  stockInsights: "/stocks/insights",
  stockLeaderboard: "/stocks/leaderboard",
  stockGainers: "/stocks/gainers",
  stockLosers: "/stocks/losers",
  mutualFunds: "/mutualfunds",
  fundBuy: "/mutualfunds/buy",
  fundSell: "/mutualfunds/sell",
  fundHoldings: "/mutualfunds/holdings",
  fundInsights: "/mutualfunds/insights",
  realEstate: "/realestate",
  properties: "/realestate/properties",
  realEstatePortfolio: "/realestate/portfolio",
  rents: "/realestate/rents",
  valuations: "/realestate/valuations",
  profile: "/profile",
  settings: "/profile/settings",
  notifications: "/profile/notifications",
  changePassword: "/profile/change-password",
  unauthorized: "/unauthorized",
} as const;
